[project]
name = "powersys_ijbd"
version = "0.0.0"
authors = [
    { name="Isaac Bromley-Dulfano", email="ijbd@umich.edu" },
    { name="Srihari Sundar", email="sriharis@umich.edu" }
]
description = "An open-source power system reliability package."
readme = "README.rst"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/ijbd/powersys.git"
"Documentation" = "https://powersys.readthedocs.io/en/latest/index.html"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
powersys = "powersys.cli
