name: Publish package
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Build test pyproject
        run: poetry build
      - name: Publish project to TestPyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository=testpypi --username=__token__ --password=${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Publish project to PyPI
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_API_TOKEN }}