name: Publish package
on: 
  push:
    paths:  
      - assetra/
      - pyproject.toml
      - .github/workflows/publish.yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Build test pyproject
        run: poetry build
      - name: Publish project to TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository=testpypi --username=__token__ --password=${{ secrets.TEST_PYPI_API_TOKEN }} 
      - name: Publish project to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_API_TOKEN }}